import 'pages/havruta/havruta.dart';

List<Question> questions = [
  Question(
    id: 1,
    category: '컴퓨터 구성',
    title: 'Half Adder 구현 관련 질문',
    content: 'Half Adder를 구성하는 중에 에러가 뜨는데 이유를 모르겠어요.',
    status: '해결 중',
    imageUrl: 'assets/images/pic1.png',
    professor: "정준호 교수님",
    good: 33,
    view: 150,
    liked: false,
  ),
  Question(
    id: 0,
    category: '신호와 시스템',
    title: '푸리에 변환 질문',
    content: '푸리에 변환할때 jw가 무슨 의미인가요?',
    status: '해결 완료',
    imageUrl: 'assets/images/pic2.png',
    professor: "손정인 교수님",
    good: 12,
    view: 122,
    liked: false,
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "고전 요가",
    title: '8단계 요가',
    content: '파탄잘리의 요가 수트라에서 제시된 "8단계 요가"는 현대 요가 실천에 어떤 영향을 미쳤습니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "고전 요가",
    title: '명상의 영향',
    content: '고전 요가의 "명상"이 신체 건강과 정신적 평화에 미치는 영향에 대해 어떻게 설명할 수 있습니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "아비달마",
    title: '5음',
    content: '아비달마 교리에서의 "5음" 개념은 무엇이며, 그것이 인간 경험을 어떻게 설명하는지 설명해 주세요.',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "아비달마",
    title: '사성제와 팔정도',
    content: '아비달마가 제시하는 "사성제"와 "팔정도"의 해석에서의 차이를 설명해 주세요.',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "중국 선사상",
    title: '좌선의 중요성',
    content: '중국 선불교에서 "좌선"의 중요성과 그가 제시하는 명상 방법에 대해 설명해 주세요.',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "중국 선사상",
    title: '무문관',
    content: '중국 선사상에서의 "무문관"(無門關)과 그것이 가진 철학적 의미를 어떻게 이해할 수 있습니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "선의 이해",
    title: '직지인심',
    content: '선불교에서 "직지인심"(直指人心)이란 무엇을 의미하며, 이를 실천하기 위한 방법은 무엇입니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "선의 이해",
    title: '여타 종교와의 차이점',
    content: '선(禅)의 "즉각적 깨달음" 개념은 다른 불교 종파의 깨달음 개념과 어떻게 다릅니까?',
  ),

  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: '인도의 철학과 문화',
    title: '업과 윤회',
    content:
        '인도의 고대 철학에서 "업"(Karma)과 "윤회"(Samsara)의 개념은 어떻게 상호작용하며 인간 존재에 영향을 미칩니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: '인도의 철학과 문화',
    title: '베다와 우파니샤드',
    content:
        '베다(Veda)와 우파니샤드(Upanishad)에서의 철학적 사고가 인도의 문화와 사회적 구조에 어떤 영향을 미쳤습니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: '불교 교단사',
    title: '교단의 조직 구조',
    content: '초기 불교 교단의 조직 구조는 어떻게 형성되었으며, 이를 통해 당시 사회에 미친 영향은 무엇입니까?',
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: '불교 교단사',
    title: '대승불교의 출현',
    content: '대승불교의 출현과 그로 인한 교단 내 변화를 설명해 주세요.',
  ),

  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 13,
    view: 132,
    liked: false,
    title: '표리에 변환 관련 질문',
    content: 'jw가 무슨 의미인가요? 도저히 이해가 안가네요',
    category: "신호와 시스템",
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 142,
    view: 1352,
    liked: false,
    title: 'Quick sort 구현 관련 질문',
    category: "신호와 시스템",
    content: "다른 Quick sort 어떤 방식으로 구현하셨나요?",
  ),

  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "신호와 시스템",
    title: "라플라스 변환 관련 질문",
    content: "라플라스가 뭐임?",
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    category: "신호와 시스템",
    content: "4X1 MUX 구현 오류 해결",
    title: "4X1 MUX 구현 오류 해결",
  ),
  Question(
    status: '해결 중',
    imageUrl: "",
    id: 2,
    professor: "",
    good: 12,
    view: 135,
    liked: false,
    title: "quick sort구현",
    category: "자료구조와 실습",
    content: "퀵소트 구현 왜이리 어렵냐. 구현한사람?",
  ),

  // 다른 질문을 추가할 수 있습니다.
];
List<Comment> commentsA1 = [
  Comment(content: 'jw는 복소수 표현에서 주파수를 나타내는 값이에요.', parentid: 1),
  Comment(content: '변환 후 주파수 영역에서 사용되는 값이죠.', parentid: 1),
];
List<Comment> commentsA2 = [
  Comment(content: "더 자세히 보여주실 수 있나요?", parentid: 0),
];

int answerCount = 2;
List<Comment> originalAnswer = [
  Comment(content: '더 자세히 보여줄 수 있나요?', parentid: 0),
  Comment(content: '주파수는 어떻게 분석할 수 있나요?', parentid: 1),
];

List<List<Comment>> answersComments = [commentsA1, commentsA2];
